import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { Environment, Type, InAppOwnershipType } from "@apple/app-store-server-library";
import { normalizeApple, normalizeGoogle, transactionKey, verifyApple } from "./providers.server";
import { accountBinding, nativeProduct, requireSandbox } from "./config.server";
import { verifyAndDeliver } from "./service.server";
import { nativeBody, nativeFailure } from "./http.server";
import { hasCityUnlock } from "../cityUnlock.server";
beforeEach(()=>{vi.stubEnv("CITYWALK_NATIVE_BILLING_MODE","sandbox");vi.stubEnv("CITYWALK_NATIVE_ACCOUNT_SECRET","s".repeat(40));vi.stubEnv("CITYWALK_NATIVE_SANDBOX_USERS","owner,other");vi.stubEnv("VERCEL_ENV","preview");vi.stubEnv("CITYWALK_GOOGLE_TEST_PURCHASES","1");vi.stubEnv("CITYWALK_GOOGLE_SERVICE_ACCOUNT",JSON.stringify({type:"service_account",client_email:"test@example.test",private_key:"synthetic-test-only"}));});
afterEach(()=>vi.unstubAllEnvs());
const apple=()=>({environment:Environment.SANDBOX,bundleId:"com.citywalk.app",productId:nativeProduct.productId,type:Type.NON_CONSUMABLE,inAppOwnershipType:InAppOwnershipType.PURCHASED,quantity:1,originalTransactionId:"original",transactionId:"transaction",appAccountToken:accountBinding("owner")});
const google=()=>({testPurchaseContext:{fopType:"TEST"},purchaseStateContext:{purchaseState:"PURCHASED"},productLineItem:[{productId:nativeProduct.productId,productOfferDetails:{quantity:1,refundableQuantity:1}}],obfuscatedExternalAccountId:accountBinding("owner")});
describe("verified Store normalization",()=>{
 it("Apple canonical identity survives transaction retries, revocation is terminal evidence",()=>{expect(normalizeApple(apple())).toMatchObject({transactionKey:transactionKey("original"),state:"purchased"});expect(normalizeApple({...apple(),revocationDate:1}).state).toBe("revoked");});
 it.each([{environment:Environment.PRODUCTION},{bundleId:"other"},{productId:"other"},{type:Type.CONSUMABLE},{quantity:2},{appAccountToken:undefined},{inAppOwnershipType:InAppOwnershipType.FAMILY_SHARED}])("rejects wrong Apple evidence %j",change=>{expect(()=>normalizeApple({...apple(),...change})).toThrow("INVALID_PURCHASE");});
 it("Google requires test payment, exact product, binding and purchased state",()=>{expect(normalizeGoogle(google(),"token")).toMatchObject({provider:"google_test",transactionKey:transactionKey("token"),state:"purchased"});expect(()=>normalizeGoogle({...google(),testPurchaseContext:undefined},"t")).toThrow();expect(()=>normalizeGoogle({...google(),obfuscatedExternalAccountId:undefined},"t")).toThrow();expect(()=>normalizeGoogle({...google(),purchaseStateContext:{purchaseState:"PENDING"}},"t")).toThrow("PURCHASE_PENDING");expect(normalizeGoogle({...google(),purchaseStateContext:{purchaseState:"CANCELLED"}},"t").state).toBe("revoked");});
 it("Google wrong product/quantity/refunded evidence cannot grant",()=>{const value=google();value.productLineItem[0].productId="wrong";expect(()=>normalizeGoogle(value,"t")).toThrow();const refunded=google();refunded.productLineItem[0].productOfferDetails.refundableQuantity=0;expect(normalizeGoogle(refunded,"t").state).toBe("revoked");});
 it("forged signed bytes cannot pass the real verifier boundary",async()=>{await expect(verifyApple("forged.client.payload")).rejects.toThrow();});
 it("sandbox grants are never honored by Production",async()=>{vi.stubEnv("VERCEL_ENV","production");expect(()=>requireSandbox()).toThrow();const findActive=vi.fn(async()=>true);expect(await hasCityUnlock({userId:"owner",citySlug:"lubeck"},{findActive})).toBe(false);expect(findActive).not.toHaveBeenCalled();});
});
function fixture(){const calls:string[]=[];const value=normalizeApple(apple());const ports={verifyApple:vi.fn(async()=>value),verifyGoogle:vi.fn(async()=>({...value,provider:"google_test" as const})),deliverNativePurchase:vi.fn(async()=>{calls.push("durable");return "active" as const;}),acknowledgeGoogle:vi.fn(async()=>{calls.push("ack");}),hasCityUnlock:vi.fn(async()=>{calls.push("read");return true;})};return {ports,calls};}
it("server identity and current provider evidence precede durable write and Google ack",async()=>{const f=fixture();expect(await verifyAndDeliver("owner","google","token",f.ports)).toEqual({delivered:true,active:true});expect(f.calls).toEqual(["durable","ack","read"]);});
it("failed durable write is never acknowledged",async()=>{const f=fixture();f.ports.deliverNativePurchase.mockRejectedValue(new Error("db"));await expect(verifyAndDeliver("owner","google","token",f.ports)).rejects.toThrow();expect(f.ports.acknowledgeGoogle).not.toHaveBeenCalled();});
it("account conflict cannot reach ledger/ack",async()=>{const f=fixture();await expect(verifyAndDeliver("other","apple","proof",f.ports)).rejects.toThrow("ACCOUNT_CONFLICT");expect(f.ports.deliverNativePurchase).not.toHaveBeenCalled();});
it("verification alone cannot unlock and ack failure can retry",async()=>{const f=fixture();f.ports.hasCityUnlock.mockResolvedValue(false);await expect(verifyAndDeliver("owner","apple","proof",f.ports)).rejects.toThrow("UNAVAILABLE");f.ports.hasCityUnlock.mockResolvedValue(true);f.ports.acknowledgeGoogle.mockRejectedValueOnce(new Error("network"));await expect(verifyAndDeliver("owner","google","proof",f.ports)).rejects.toThrow();await expect(verifyAndDeliver("owner","google","proof",f.ports)).resolves.toEqual({delivered:true,active:true});expect(f.ports.verifyGoogle).toHaveBeenCalledTimes(2);});
it("safe errors never serialize tokens or provider payloads",async()=>{expect(await nativeFailure(new Error("secret receipt token")).text()).toBe('{"code":"UNAVAILABLE"}');});
it("rejects oversized/invalid notification bodies before provider work",async()=>{await expect(nativeBody(new Request("https://preview.test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signedPayload:"x".repeat(33000)})}))).rejects.toThrow();await expect(nativeBody(new Request("https://preview.test",{method:"POST",headers:{"Content-Type":"application/json"},body:"[]"}))).rejects.toThrow();});
it("revocation detected during Google acknowledgement revokes the just-delivered grant",async()=>{
 const f=fixture();const {NativeBillingError}=await import("./config.server");f.ports.acknowledgeGoogle.mockRejectedValueOnce(new NativeBillingError("PURCHASE_REVOKED",409));await expect(verifyAndDeliver("owner","google","proof",f.ports)).rejects.toThrow("PURCHASE_REVOKED");expect(f.ports.deliverNativePurchase).toHaveBeenLastCalledWith(expect.objectContaining({state:"revoked"}));expect(f.ports.hasCityUnlock).not.toHaveBeenCalled();
});
